language: python
sudo: false
dist: focal
python:
  - "3.9-dev"
  - "3.8"
  - "3.7"
  - "3.6"
addons:
  apt:
    packages:
    - libgmp-dev
install:
  - "./cddlib-makefile-gmp.sh"
  - pip install --install-option="--no-cython-compile" Cython
  - "pip install Sphinx"
  - "pip install pytest"
  - "pip install numpy"
  - "pip install ."
script:
  - "pytest"
  - "cd docs"
  - "make doctest"
